# Mab Lib

print('Create your own mad lib!')
print()
 # telesales marketer

fn = input('Someone\'s first name:  ')
ln = input('Someone\'s last name:  ')
afn = input('Another person\'s first name:  ')
aln = input('Another person\'s last name:  ')
c = input('Name of a company:  ')
act = input('Activity that you like to do:  ')
cn = input('Name or type of charity (it can be fictitious):  ')
adj1 = input('Adjective:  ')
noun = input('Noun:  ')
num1 = input('Number:  ')
adj2 = input('Adjective:  ')
plnoun1 = input('Plural noun:  ')
adj3 = input('Adjective:  ')
num2 = input('Number:  ')
plnoun2 = input('Plural noun:  ')
print()
print('Call From a Telemarketer')
print(f'{fn}: Hello?')
print()
print(f'Telemarketer: Hello, this is {afn}, {aln} from {c}. May I please speak with {fn} {ln}?')
print()
print(f'{fn}: That\'s me. I\'m just about to {act}, and...')
print()
print(f'Telemarketer: {fn}, I\'m calling today to see if you are interested in donating to our {cn} fund by purchasing our new product, called {adj1} {noun}.')
print(f'Prices start from only ${num1}, and you can have your very own {adj1} {noun} delivered to your house by tomorrow morning!')
print()
print(f'{fn}: I\'m not interested, thank you.')
print()
print(f'Telemarketer: Are you sure? This is an opportunity of a lifetime! You will help thousands of {adj2} {plnoun1} by purchasing {adj1} {noun}, and if you purchase today, we will also send you {num2} {adj3} {plnoun2}.')
print()
print(f'{fn}: No thank you.')
print()
print(f'Telemarketer: Don\'t let this opportunity slip through your fingers. Very few people own {adj1} {noun}, and this is a limited offer.')
print()
print(f'{fn}: No thanks! Goodbye! (phone click).')
